### ISSUE TITLE
Please provide example for insert data in postgresql database

### ISSUE THREAD

**Issue by ganeshjangid** [Claviz/bellboy#18]
Below code is not storing data in database from excel file

 const processor = new bellboy.ExcelProcessor({
        path: directoryPath,
        hasHeader: true,
      });

      const destination = new bellboy.PostgresDestination({
        connection: {
          user: "postgres",
          password: "123456",
          server: "localhost",
          database: "ITA_projects",
        },
        table: "ita",
        upsertConstraints:"inserts",
        recordGenerator: async function* (record) {
          //console.log(record);
          yield {
            ...record.raw.obj,
            status: "done",
          };
        },
      });
      //console.log("show destination==>", destination);

      const job = new bellboy.Job(processor, [destination])

      job.on("endProcessingStream", async (file) => {
        const filePath = path.join(directoryPath, file);
        const newFilePath = path.join(
          __dirname,
          "..",
          "..",
          "..",
          "destination",
          file
        );
        await fs.renameSync(filePath, newFilePath);
      });
      await job.run();

**Comment by jansivans** [comment]
Hi!
Try to change `server` to `host` in `connection` object.
You can check code examples for posgres destination [here](https://github.com/Claviz/bellboy/blob/master/tests/postgres-destination.spec.ts).

If things above didn't help, you can try to `console.log` events to check if there is some error.
You can do this using `job.onAny` event listener:
```js
job.onAny(async (eventName, ...args) => {
    console.log(args);
});
```

**Comment by ganeshjangid** [comment]
thanks for help , 

const processor = new bellboy.ExcelProcessor({
path: directoryPath,
hasHeader: true,
});

in there , can i call only specific file

**Comment by jansivans** [comment]
Yes, you can.
Use `files` array:
```js
const processor = new bellboy.ExcelProcessor({
  path: directoryPath,
  hasHeader: true,
  files: ['file1.xlsx']
});
```

**Comment by jansivans** [comment]
Please provide full example so I could reproduce this.

**Comment by ganeshjangid** [comment]
I have one excel file and there are 2 columns and 2 rows just like below table 

baureihe |	software_release
25645     |
ORC223  |  191103
 
After 25645 column there is blank column. it does not take blank column value in database 




Error: Property 'column_11' doesn't exist.
[1]       at C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\formatting.js:166:19
[1]       at String.replace (<anonymous>)
[1]       at Object.object (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\formatting.js:146:22)
[1]       at formatQuery (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\formatting.js:300:29)
[1]       at format (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\formatting.js:852:16)
[1]       at C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\helpers\methods\insert.js:137:26
[1]       at Array.map (<anonymous>)
[1]       at Object.insert (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\helpers\methods\insert.js:133:29)
[1]       at Object.insert (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\helpers\index.js:53:27)
[1]       at PostgresDestination.<anonymous> (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\bellboy\lib\destinations\postgres-destination.js:94:57)
[1]       at step (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\bellboy\lib\destinations\postgres-destination.js:46:23)
[1]       at Object.next (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\bellboy\lib\destinations\postgres-destination.js:27:53)
[1]       at C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\bellboy\lib\destinations\postgres-destination.js:21:71
[1]       at new Promise (<anonymous>)
[1]       at __awaiter (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\bellboy\lib\destinations\postgres-destination.js:17:12)
[1]       at Task.<anonymous> (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\bellboy\lib\destinations\postgres-destination.js:91:74)
[1]       at callback (C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\task.js:201:21)
[1]       at C:\Users\sutharg\Desktop\ganesh\ITA_projects\ITA\node_modules\pg-promise\lib\task.js:261:25
[1]       at processTicksAndRejections (internal/process/task_queues.js:93:5)
[1] ]

**Comment by ganeshjangid** [comment]
const processor = new bellboy.ExcelProcessor({
        path: directoryPath,
        hasHeader: true,
        files:[files["filename"]]
      });

      const destination = new bellboy.PostgresDestination({
        connection: {
          user: "postgres",
          password: "123456",
          host: "localhost",
          database: "ITA_projects",
        },
        table: "ita",
        recordGenerator: async function* (record) {
          //console.log(record);
          yield {
            ...record.raw.obj,
            status: "done",
          };
        },
      });

      //console.log("show destination==>", destination);

      const job = new bellboy.Job(processor, [destination])
      job.onAny(async (eventName, ...args) => {
          console.log(args);
      });

      await job.run();

**Comment by jansivans** [comment]
You can check records inside `recordGenerator` and modify value here before `yield`.
You can even skip `yield` if some data is not appropriate for you.

**Comment by jansivans** [comment]
For example,
```js
recordGenerator: async function* (record) {
  const obj = record.raw.obj;
  if (obj.someField !== 123) {
    yield {
      ...record.raw.obj,
      status: "done",
    };
  }
},
```

**Comment by AlexTimo** [comment]
@ganeshjangid,

you can also do explicit mapping to your database columns, thus always having all fields in every generated record, even if some values are null:

```
recordGenerator: async function* (record) {
	const obj = record.raw.obj;
	yield {
		"baureihe": obj.baureihe,
		"software_release": obj.software_release,
	};
},
```

**Comment by ganeshjangid** [comment]
i want , if column value is blank in row then should not ignore and add in object

**Comment by ganeshjangid** [comment]
thanks for help, can i set my own header column name

**Comment by AlexTimo** [comment]
Hi @ganeshjangid ,

have you been able to load the data, can I close this issue now?

**Comment by ganeshjangid** [comment]
Yes
